"""
services/corpus_service.py
==========================
Cinephile Universe Corpus Engine.
Manages a curated database of top-tier cinema masterworks spanning
Sight & Sound 250, Criterion Collection, Letterboxd Top 1000, Palme d'Or,
Venice/Berlin winners, and historical film movements with rich craft metadata.

Features:
- Instant in-memory / SQLite caching (< 2ms retrieval).
- Balanced 3-Era Temporal Structure:
  1. Contemporary Era (2010–2026)
  2. Modern Cult & Indie Renaissance (1980–2009)
  3. Golden Age Monoliths (< 1980)
- Rich Craft representation (Director, DoP, Composer, Screenwriter, Studio, Country, Era).
"""

import os
import sqlite3
import json
import logging
from typing import List, Dict, Any, Optional

logger = logging.getLogger(__name__)

DB_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "instance")
CORPUS_DB_PATH = os.path.join(DB_DIR, "cinephile_corpus.db")

_IN_MEMORY_CORPUS_CACHE: Optional[List[Dict[str, Any]]] = None


def _init_corpus_db():
    """Initializes the SQLite corpus schema."""
    os.makedirs(DB_DIR, exist_ok=True)
    with sqlite3.connect(CORPUS_DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS curated_films (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                movie_key TEXT UNIQUE,
                title TEXT NOT NULL,
                year INTEGER NOT NULL,
                director TEXT NOT NULL,
                genre TEXT NOT NULL,
                cinematographer TEXT DEFAULT '',
                composer TEXT DEFAULT '',
                screenwriter TEXT DEFAULT '',
                studios TEXT DEFAULT '',
                lead_actors TEXT DEFAULT '',
                country TEXT DEFAULT 'US',
                language TEXT DEFAULT 'en',
                overview TEXT DEFAULT '',
                poster TEXT DEFAULT '',
                tv_show INTEGER DEFAULT 0,
                canon_tier TEXT DEFAULT 'landmark',
                movement_tags TEXT DEFAULT '',
                rating_score REAL DEFAULT 8.0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_curated_key ON curated_films(movie_key)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_curated_director ON curated_films(director)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_curated_genre ON curated_films(genre)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_curated_year ON curated_films(year)")


def _normalize_key(title: str, year: Any) -> str:
    import re
    t = re.sub(r"[^\w\s]", "", str(title or "").lower()).strip()
    t = re.sub(r"\s+", "", t)
    y = str(year or "").strip()[:4]
    return f"{t}_{y}"


# Master Cinephile Landmark Corpus (Over 140+ Highly Curated Masterworks Balanced Across Eras)
CORE_CINEPHILE_MASTERWORKS = [
    # =========================================================================
    # 1. CONTEMPORARY VISIONARIES & FESTIVAL LANDMARKS (2010 – 2026)
    # =========================================================================
    {"title": "The Zone of Interest", "year": 2023, "director": "Jonathan Glazer", "genre": "Drama, History, War", "cinematographer": "Łukasz Żal", "composer": "Mica Levi", "screenwriter": "Jonathan Glazer", "country": "GB", "language": "de", "canon_tier": "palme_dor_festival", "movement_tags": "A24, Banality of Evil, Fixed Camera Geometries, Mica Levi Soundscape", "rating_score": 8.6},
    {"title": "Anatomy of a Fall", "year": 2023, "director": "Justine Triet", "genre": "Crime, Drama, Mystery, Thriller", "cinematographer": "Simon Beaufils", "composer": "None", "screenwriter": "Justine Triet, Arthur Harari", "country": "FR", "language": "fr", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Courtroom Deconstruction, French Modern Masterpiece", "rating_score": 8.7},
    {"title": "Past Lives", "year": 2023, "director": "Celine Song", "genre": "Drama, Romance", "cinematographer": "Shabier Kirchner", "composer": "Christopher Bear, Daniel Rossen", "screenwriter": "Celine Song", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, In-Yun Destiny, Melancholy Romance, Quiet Masterwork", "rating_score": 8.6},
    {"title": "Poor Things", "year": 2023, "director": "Yorgos Lanthimos", "genre": "Comedy, Drama, Romance, Sci-Fi", "cinematographer": "Robbie Ryan", "composer": "Jerskin Fendrix", "screenwriter": "Tony McNamara", "country": "GB", "language": "en", "canon_tier": "palme_dor_festival", "movement_tags": "Venice Golden Lion, Surreal Victorian, Lanthimos Absurdism", "rating_score": 8.6},
    {"title": "Tár", "year": 2022, "director": "Todd Field", "genre": "Drama, Music", "cinematographer": "Florian Hoffmeister", "composer": "Hildur Guðnadóttir", "screenwriter": "Todd Field", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Psychological Power Study, Symphony Orchestral, Modern Auteur", "rating_score": 8.7},
    {"title": "Decision to Leave", "year": 2022, "director": "Park Chan-wook", "genre": "Crime, Drama, Mystery, Romance", "cinematographer": "Kim Ji-yong", "composer": "Cho Young-wuk", "screenwriter": "Park Chan-wook, Chung Seo-kyung", "country": "KR", "language": "ko", "canon_tier": "palme_dor_festival", "movement_tags": "Cannes Best Director, Modern Hitchcockian Romance, Foggy Mountain Noir", "rating_score": 8.7},
    {"title": "Aftersun", "year": 2022, "director": "Charlotte Wells", "genre": "Drama", "cinematographer": "Gregory Oke", "composer": "Oliver Coates", "screenwriter": "Charlotte Wells", "country": "GB", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, MiniDV Nostalgia, Paternal Melancholy, British Indie Masterpiece", "rating_score": 8.7},
    {"title": "The Banshees of Inisherin", "year": 2022, "director": "Martin McDonagh", "genre": "Comedy, Drama", "cinematographer": "Ben Davis", "composer": "Carter Burwell", "screenwriter": "Martin McDonagh", "country": "IE", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Irish Existential Comedy, McDonagh Dialogue, Island Feud", "rating_score": 8.5},
    {"title": "The Worst Person in the World", "year": 2021, "director": "Joachim Trier", "genre": "Comedy, Drama, Romance", "cinematographer": "Kasper Tuxen", "composer": "Ola Fløttum", "screenwriter": "Joachim Trier, Eskil Vogt", "country": "NO", "language": "no", "canon_tier": "letterboxd_top", "movement_tags": "Oslo Trilogy Finale, Existential Romance, Modern Millennial Cinema", "rating_score": 8.6},
    {"title": "Drive My Car", "year": 2021, "director": "Ryūsuke Hamaguchi", "genre": "Drama", "cinematographer": "Hidetoshi Shinomiya", "composer": "Eiko Ishibashi", "screenwriter": "Ryūsuke Hamaguchi, Takamasa Oe", "country": "JP", "language": "ja", "canon_tier": "palme_dor_festival", "movement_tags": "Murakami Adaptation, Therapeutic Travel, Modern Japanese Masterpiece", "rating_score": 8.8},
    {"title": "The Hand of God", "year": 2021, "director": "Paolo Sorrentino", "genre": "Drama", "cinematographer": "Daria D'Antonio", "composer": "Lele Marchitelli", "screenwriter": "Paolo Sorrentino", "country": "IT", "language": "it", "canon_tier": "letterboxd_top", "movement_tags": "Neapolitan Autobiographical, Coming of Age, Melancholy Comedy", "rating_score": 8.5},
    {"title": "First Cow", "year": 2019, "director": "Kelly Reichardt", "genre": "Drama", "cinematographer": "Christopher Blauvelt", "composer": "William Tyler", "screenwriter": "Kelly Reichardt, Jonathan Raymond", "country": "US", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "A24, Oregon Frontier, Tender Friendship, Slow American Cinema", "rating_score": 8.4},
    {"title": "Portrait of a Lady on Fire", "year": 2019, "director": "Céline Sciamma", "genre": "Drama, Romance, History", "cinematographer": "Claire Mathon", "composer": "Jean-Baptiste de Laubier, Arthur Simonini", "screenwriter": "Céline Sciamma", "country": "FR", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "Cannes Screenplay, Female Gaze, Modern Queer Masterpiece, Sensory Art", "rating_score": 8.9},
    {"title": "Parasite", "year": 2019, "director": "Bong Joon-ho", "genre": "Comedy, Drama, Thriller", "cinematographer": "Hong Kyung-pyo", "composer": "Jung Jae-il", "screenwriter": "Bong Joon-ho, Han Jin-won", "country": "KR", "language": "ko", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Class Satire, Architectural Metaphor, Korean Golden Wave", "rating_score": 9.0},
    {"title": "Uncut Gems", "year": 2019, "director": "Josh Safdie, Benny Safdie", "genre": "Crime, Drama, Thriller", "cinematographer": "Darius Khondji", "composer": "Daniel Lopatin", "screenwriter": "Josh Safdie, Benny Safdie, Ronald Bronstein", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, Diamond District Panic, Oneohtrix Point Never Synth, Safdie Kinetic", "rating_score": 8.5},
    {"title": "The Lighthouse", "year": 2019, "director": "Robert Eggers", "genre": "Drama, Fantasy, Horror, Mystery", "cinematographer": "Jarin Blaschke", "composer": "Mark Korven", "screenwriter": "Robert Eggers, Max Eggers", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, 1.19:1 Monochrome, Mythological Madness, Foghorn Horror", "rating_score": 8.5},
    {"title": "Burning", "year": 2018, "director": "Lee Chang-dong", "genre": "Drama, Mystery, Thriller", "cinematographer": "Hong Kyung-pyo", "composer": "Mowg", "screenwriter": "Lee Chang-dong, Oh Jung-mi", "country": "KR", "language": "ko", "canon_tier": "letterboxd_top", "movement_tags": "Cannes FIPRESCI Winner, Murakami Adaptation, Korean Slow Burn, Existential Rage", "rating_score": 8.7},
    {"title": "Cold War", "year": 2018, "director": "Paweł Pawlikowski", "genre": "Drama, History, Music, Romance", "cinematographer": "Łukasz Żal", "composer": "Marcin Masecki", "screenwriter": "Paweł Pawlikowski, Janusz Głowacki", "country": "PL", "language": "pl", "canon_tier": "criterion_essential", "movement_tags": "Cannes Best Director, 4:3 Monochrome, Polish Folk Jazz, Tragic Love", "rating_score": 8.6},
    {"title": "Roma", "year": 2018, "director": "Alfonso Cuarón", "genre": "Drama", "cinematographer": "Alfonso Cuarón", "composer": "None", "screenwriter": "Alfonso Cuarón", "country": "MX", "language": "es", "canon_tier": "criterion_essential", "movement_tags": "Venice Golden Lion, 65mm Monochrome, Mexico City Memory, Dolby Atmos Masterclass", "rating_score": 8.7},
    {"title": "Shoplifters", "year": 2018, "director": "Hirokazu Kore-eda", "genre": "Drama, Crime", "cinematographer": "Ryūto Kondō", "composer": "Haruomi Hosono", "screenwriter": "Hirokazu Kore-eda", "country": "JP", "language": "ja", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Japanese Humanism, Chosen Family, Hosono Score", "rating_score": 8.6},
    {"title": "Phantom Thread", "year": 2017, "director": "Paul Thomas Anderson", "genre": "Drama, Romance", "cinematographer": "Paul Thomas Anderson", "composer": "Jonny Greenwood", "screenwriter": "Paul Thomas Anderson", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "House of Woodcock, Romantic Poison, Greenwood Orchestral, 35mm Elegance", "rating_score": 8.8},
    {"title": "Blade Runner 2049", "year": 2017, "director": "Denis Villeneuve", "genre": "Drama, Mystery, Sci-Fi, Thriller", "cinematographer": "Roger Deakins", "composer": "Hans Zimmer, Benjamin Wallfisch", "screenwriter": "Hampton Fancher, Michael Green", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Deakins Color Brutalism, Replicant Solitude, High-Art Sci-Fi", "rating_score": 8.9},
    {"title": "The Florida Project", "year": 2017, "director": "Sean Baker", "genre": "Comedy, Drama", "cinematographer": "Alexis Zabé", "composer": "Lorne Balfe", "screenwriter": "Sean Baker, Chris Bergoch", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, 35mm Neon Florida, Childhood Innocence, Baker Street Realism", "rating_score": 8.5},
    {"title": "Call Me by Your Name", "year": 2017, "director": "Luca Guadagnino", "genre": "Drama, Romance", "cinematographer": "Sayombhu Mukdeeprom", "composer": "Sufjan Stevens", "screenwriter": "James Ivory", "country": "IT", "language": "it", "canon_tier": "letterboxd_top", "movement_tags": "Lombardy Summer, Sufjan Stevens Score, Guadagnino Sensuality", "rating_score": 8.6},
    {"title": "The Square", "year": 2017, "director": "Ruben Östlund", "genre": "Comedy, Drama", "cinematographer": "Fredrik Wenzel", "composer": "None", "screenwriter": "Ruben Östlund", "country": "SE", "language": "sv", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Art World Satire, Nordic Social Awkwardness", "rating_score": 8.4},
    {"title": "The Handmaiden", "year": 2016, "director": "Park Chan-wook", "genre": "Drama, Romance, Thriller", "cinematographer": "Chung Chung-hoon", "composer": "Cho Young-wuk", "screenwriter": "Park Chan-wook, Chung Seo-kyung", "country": "KR", "language": "ko", "canon_tier": "criterion_essential", "movement_tags": "Korean Baroque Thriller, Erotic Twist, Symmetrical Elegance", "rating_score": 8.8},
    {"title": "Toni Erdmann", "year": 2016, "director": "Maren Ade", "genre": "Comedy, Drama", "cinematographer": "Patrick Orth", "composer": "None", "screenwriter": "Maren Ade", "country": "DE", "language": "de", "canon_tier": "palme_dor_festival", "movement_tags": "German Modern Comedy, Father-Daughter Absurdism, Cannes Sensation", "rating_score": 8.5},
    {"title": "Manchester by the Sea", "year": 2016, "director": "Kenneth Lonergan", "genre": "Drama", "cinematographer": "Jody Lee Lipes", "composer": "Lesley Barber", "screenwriter": "Kenneth Lonergan", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Unresolved Grief, New England Winter, Lonergan Naturalism", "rating_score": 8.6},
    {"title": "Arrival", "year": 2016, "director": "Denis Villeneuve", "genre": "Drama, Mystery, Sci-Fi", "cinematographer": "Bradford Young", "composer": "Jóhann Jóhannsson", "screenwriter": "Eric Heisserer", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Non-Linear Linguistics, Bradford Young Shadows, Emotional Sci-Fi", "rating_score": 8.7},
    {"title": "Sicario", "year": 2015, "director": "Denis Villeneuve", "genre": "Action, Crime, Drama, Mystery, Thriller", "cinematographer": "Roger Deakins", "composer": "Jóhann Jóhannsson", "screenwriter": "Taylor Sheridan", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Borderline Bleakness, Percussive Tension, Thermal Cam Shots", "rating_score": 8.6},
    {"title": "Son of Saul", "year": 2015, "director": "László Nemes", "genre": "Drama, War", "cinematographer": "Mátyás Erdély", "composer": "László Melis", "screenwriter": "László Nemes, Clara Royer", "country": "HU", "language": "hu", "canon_tier": "criterion_essential", "movement_tags": "Grand Prix Cannes, 40mm Shallow Focus, Sensory Immersive Sound", "rating_score": 8.6},
    {"title": "The Lobster", "year": 2015, "director": "Yorgos Lanthimos", "genre": "Comedy, Drama, Romance, Sci-Fi", "cinematographer": "Thimios Bakatakis", "composer": "None", "screenwriter": "Yorgos Lanthimos, Efthimis Filippou", "country": "GR", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "A24, Greek Weird Wave in English, Monotone Dystopian Comedy", "rating_score": 8.4},
    {"title": "Carol", "year": 2015, "director": "Todd Haynes", "genre": "Drama, Romance", "cinematographer": "Edward Lachman", "composer": "Carter Burwell", "screenwriter": "Phyllis Nagy", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Super 16mm Grain, Mid-Century Melodrama, Burwell Score", "rating_score": 8.6},
    {"title": "Ida", "year": 2013, "director": "Paweł Pawlikowski", "genre": "Drama", "cinematographer": "Łukasz Żal, Ryszard Lenczewski", "composer": "None", "screenwriter": "Paweł Pawlikowski, Rebecca Lenkiewicz", "country": "PL", "language": "pl", "canon_tier": "criterion_essential", "movement_tags": "4:3 Headroom Framing, Polish Monastery Monochrome, Modern Classic", "rating_score": 8.6},
    {"title": "The Great Beauty", "year": 2013, "director": "Paolo Sorrentino", "genre": "Drama", "cinematographer": "Luca Bigazzi", "composer": "Lele Marchitelli", "screenwriter": "Paolo Sorrentino, Umberto Contarello", "country": "IT", "language": "it", "canon_tier": "palme_dor_festival", "movement_tags": "Modern Roman Decadence, Sensory Melancholy, Italian Masterwork", "rating_score": 8.8},
    {"title": "Under the Skin", "year": 2013, "director": "Jonathan Glazer", "genre": "Drama, Horror, Sci-Fi", "cinematographer": "Daniel Landin", "composer": "Mica Levi", "screenwriter": "Walter Campbell, Jonathan Glazer", "country": "GB", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "Alien Scotland, Hidden Cam Voyeurism, Microtonal Horror", "rating_score": 8.6},
    {"title": "Inside Llewyn Davis", "year": 2013, "director": "Joel Coen, Ethan Coen", "genre": "Comedy, Drama, Music", "cinematographer": "Bruno Delbonnel", "composer": "T Bone Burnett", "screenwriter": "Joel Coen, Ethan Coen", "country": "US", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "Greenwich Village Folk, Winter Desolation, Coen Greek Myth", "rating_score": 8.7},
    {"title": "Her", "year": 2013, "director": "Spike Jonze", "genre": "Drama, Romance, Sci-Fi", "cinematographer": "Hoyte van Hoytema", "composer": "Arcade Fire, Owen Pallett", "screenwriter": "Spike Jonze", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Warm Future Aesthetics, Solitary Intimacy, Pastel Palette", "rating_score": 8.7},
    {"title": "Only Lovers Left Alive", "year": 2013, "director": "Jim Jarmusch", "genre": "Comedy, Drama, Fantasy, Horror, Music, Romance", "cinematographer": "Yorick Le Saux", "composer": "Jozef van Wissem, SQÜRL", "screenwriter": "Jim Jarmusch", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Tangier & Detroit Vampires, Lute Drone Music, Jarmusch Cool", "rating_score": 8.5},
    {"title": "The Master", "year": 2012, "director": "Paul Thomas Anderson", "genre": "Drama", "cinematographer": "Mihai Mălaimare Jr.", "composer": "Jonny Greenwood", "screenwriter": "Paul Thomas Anderson", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "65mm Portraiture, Post-War Drifter, Cult Psychology", "rating_score": 8.8},
    {"title": "Holy Motors", "year": 2012, "director": "Leos Carax", "genre": "Drama, Fantasy", "cinematographer": "Caroline Champetier, Yves Cape", "composer": "Neil Hannon", "screenwriter": "Leos Carax", "country": "FR", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "French Avant-Garde, Cinema Eulogy, Denis Lavant Shape-Shifter", "rating_score": 8.5},
    {"title": "Amour", "year": 2012, "director": "Michael Haneke", "genre": "Drama, Romance", "cinematographer": "Darius Khondji", "composer": "None", "screenwriter": "Michael Haneke", "country": "FR", "language": "fr", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Uncompromising Aging, Haneke Parisian Apartment", "rating_score": 8.7},
    {"title": "The Hunt", "year": 2012, "director": "Thomas Vinterberg", "genre": "Drama", "cinematographer": "Charlotte Bruus Christensen", "composer": "Nikolaj Egelund", "screenwriter": "Thomas Vinterberg, Tobias Lindholm", "country": "DK", "language": "da", "canon_tier": "letterboxd_top", "movement_tags": "Danish Psychological Drama, Mass Hysteria, Mads Mikkelsen Tour de Force", "rating_score": 8.8},
    {"title": "A Separation", "year": 2011, "director": "Asghar Farhadi", "genre": "Drama, Mystery", "cinematographer": "Mahmoud Kalari", "composer": "Sattar Oraki", "screenwriter": "Asghar Farhadi", "country": "IR", "language": "fa", "canon_tier": "sight_and_sound", "movement_tags": "Berlin Golden Bear, Moral Labyrinth, Iranian Masterwork", "rating_score": 8.9},
    {"title": "The Tree of Life", "year": 2011, "director": "Terrence Malick", "genre": "Drama, Fantasy", "cinematographer": "Emmanuel Lubezki", "composer": "Alexandre Desplat", "screenwriter": "Terrence Malick", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Palme d'Or Winner, Cosmic Grace, Lubezki Wide Angle, Malick Poetry", "rating_score": 8.7},
    {"title": "Melancholia", "year": 2011, "director": "Lars von Trier", "genre": "Drama, Sci-Fi", "cinematographer": "Manuel Alberto Claro", "composer": "Richard Wagner", "screenwriter": "Lars von Trier", "country": "DK", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "Tristan und Isolde Overture, Depression Cosmic Collision, Von Trier Vision", "rating_score": 8.5},
    {"title": "Incendies", "year": 2010, "director": "Denis Villeneuve", "genre": "Drama, Mystery, War", "cinematographer": "André Turpin", "composer": "Grégoire Hetzel", "screenwriter": "Denis Villeneuve, Valérie Beaugrand-Champagne", "country": "CA", "language": "fr", "canon_tier": "letterboxd_top", "movement_tags": "Middle Eastern Tragedy, Radiohead Score, Shock Epiphany", "rating_score": 8.8},
    {"title": "Poetry", "year": 2010, "director": "Lee Chang-dong", "genre": "Drama", "cinematographer": "Choi Hyun-cheol", "composer": "None", "screenwriter": "Lee Chang-dong", "country": "KR", "language": "ko", "canon_tier": "palme_dor_festival", "movement_tags": "Cannes Best Screenplay, Korean Moral Beauty, Yoon Jeong-hee Masterpiece", "rating_score": 8.6},

    # =========================================================================
    # 2. MODERN CULT & INDIE RENAISSANCE (1980 – 2009)
    # =========================================================================
    {"title": "The White Ribbon", "year": 2009, "director": "Michael Haneke", "genre": "Drama, Mystery", "cinematographer": "Christian Berger", "composer": "None", "screenwriter": "Michael Haneke", "country": "DE", "language": "de", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, High-Contrast B&W, Origin of Fascism", "rating_score": 8.7},
    {"title": "Synecdoche, New York", "year": 2008, "director": "Charlie Kaufman", "genre": "Comedy, Drama", "cinematographer": "Frederick Elmes", "composer": "Jon Brion", "screenwriter": "Charlie Kaufman", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Meta-Theatrical Life Replica, Kaufman Existential Epic, Mortality", "rating_score": 8.6},
    {"title": "In Bruges", "year": 2008, "director": "Martin McDonagh", "genre": "Comedy, Crime, Drama", "cinematographer": "Eigil Bryld", "composer": "Carter Burwell", "screenwriter": "Martin McDonagh", "country": "GB", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Medieval Purgatory, Hitman Philosophy, Carter Burwell Piano", "rating_score": 8.7},
    {"title": "Il Divo", "year": 2008, "director": "Paolo Sorrentino", "genre": "Biography, Crime, Drama", "cinematographer": "Luca Bigazzi", "composer": "Teho Teardo", "screenwriter": "Paolo Sorrentino", "country": "IT", "language": "it", "canon_tier": "palme_dor_festival", "movement_tags": "Cannes Jury Prize, Political Baroque, Kinetic Style, Andreotti", "rating_score": 8.5},
    {"title": "There Will Be Blood", "year": 2007, "director": "Paul Thomas Anderson", "genre": "Drama", "cinematographer": "Robert Elswit", "composer": "Jonny Greenwood", "screenwriter": "Paul Thomas Anderson", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "American Capitalism Nightmare, Microtonal Strings, Monolithic Acting", "rating_score": 9.1},
    {"title": "No Country for Old Men", "year": 2007, "director": "Joel Coen, Ethan Coen", "genre": "Crime, Drama, Thriller", "cinematographer": "Roger Deakins", "composer": "Carter Burwell", "screenwriter": "Joel Coen, Ethan Coen", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "West Texas Nihilism, Ambient Wind Silence, Unstoppable Fate", "rating_score": 9.0},
    {"title": "4 Months, 3 Weeks and 2 Days", "year": 2007, "director": "Cristian Mungiu", "genre": "Drama", "cinematographer": "Oleg Mutu", "composer": "None", "screenwriter": "Cristian Mungiu", "country": "RO", "language": "ro", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Romanian New Wave, Real-Time Tension", "rating_score": 8.6},
    {"title": "The Assassination of Jesse James by the Coward Robert Ford", "year": 2007, "director": "Andrew Dominik", "genre": "Biography, Crime, Drama, Western", "cinematographer": "Roger Deakins", "composer": "Nick Cave, Warren Ellis", "screenwriter": "Andrew Dominik", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Deakins Vintage Lenses, Nick Cave Score, Poetic Western Tragedy", "rating_score": 8.7},
    {"title": "Children of Men", "year": 2006, "director": "Alfonso Cuarón", "genre": "Action, Drama, Sci-Fi, Thriller", "cinematographer": "Emmanuel Lubezki", "composer": "John Tavener", "screenwriter": "Alfonso Cuarón, Timothy J. Sexton, David Arata", "country": "GB", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Single-Take Dystopia, Lubezki Handheld, London Collapse", "rating_score": 8.9},
    {"title": "Pan's Labyrinth", "year": 2006, "director": "Guillermo del Toro", "genre": "Drama, Fantasy, War", "cinematographer": "Guillermo Navarro", "composer": "Javier Navarrete", "screenwriter": "Guillermo del Toro", "country": "ES", "language": "es", "canon_tier": "letterboxd_top", "movement_tags": "Dark Fairy Tale, Spanish Civil War, Practical Creatures", "rating_score": 8.8},
    {"title": "The Lives of Others", "year": 2006, "director": "Florian Henckel von Donnersmarck", "genre": "Drama, Mystery, Thriller", "cinematographer": "Hagen Bogdanski", "composer": "Gabriel Yared, Stéphane Moucha", "screenwriter": "Florian Henckel von Donnersmarck", "country": "DE", "language": "de", "canon_tier": "letterboxd_top", "movement_tags": "Stasi Surveillance, Sonata for a Good Man, Humanist Awakening", "rating_score": 8.9},
    {"title": "Caché", "year": 2005, "director": "Michael Haneke", "genre": "Drama, Mystery, Thriller", "cinematographer": "Christian Berger", "composer": "None", "screenwriter": "Michael Haneke", "country": "FR", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "Cannes Best Director, Surveillance Paranoia, Post-Colonial Guilt", "rating_score": 8.7},
    {"title": "Brokeback Mountain", "year": 2005, "director": "Ang Lee", "genre": "Drama, Romance, Western", "cinematographer": "Rodrigo Prieto", "composer": "Gustavo Santaolalla", "screenwriter": "Larry McMurtry, Diana Ossana", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Wyoming Landscape, Santaolalla Guitar, Heartbreaking Melodrama", "rating_score": 8.7},
    {"title": "The Consequences of Love", "year": 2004, "director": "Paolo Sorrentino", "genre": "Crime, Drama, Mystery", "cinematographer": "Luca Bigazzi", "composer": "Pasquale Catalano", "screenwriter": "Paolo Sorrentino", "country": "IT", "language": "it", "canon_tier": "letterboxd_top", "movement_tags": "Italian Neo-Noir, Stylized Precision, Cold Solitude, Sorrentino Masterwork", "rating_score": 8.6},
    {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "director": "Michel Gondry", "genre": "Drama, Romance, Sci-Fi", "cinematographer": "Ellen Kuras", "composer": "Jon Brion", "screenwriter": "Charlie Kaufman, Michel Gondry, Pierre Bismuth", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Memory Erasure Romance, Practical Gondry Effects, Melancholy Winter", "rating_score": 8.9},
    {"title": "Before Sunset", "year": 2004, "director": "Richard Linklater", "genre": "Drama, Romance", "cinematographer": "Lee Daniel", "composer": "None", "screenwriter": "Richard Linklater, Julie Delpy, Ethan Hawke", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Real-Time Paris Walk, Conversational Magic, Romance Masterpiece", "rating_score": 8.8},
    {"title": "2046", "year": 2004, "director": "Wong Kar-wai", "genre": "Drama, Romance, Sci-Fi", "cinematographer": "Christopher Doyle, Lai Yiu-fai, Kwan Pun-leung", "composer": "Shigeru Umebayashi, Peer Raben", "screenwriter": "Wong Kar-wai", "country": "HK", "language": "yue", "canon_tier": "criterion_essential", "movement_tags": "Hong Kong Second Wave, Sci-Fi Nostalgia, Lush Saturated Colors", "rating_score": 8.5},
    {"title": "Oldboy", "year": 2003, "director": "Park Chan-wook", "genre": "Action, Drama, Mystery, Thriller", "cinematographer": "Chung Chung-hoon", "composer": "Cho Young-wuk", "screenwriter": "Park Chan-wook, Hwang Jo-yun, Lim Joon-hyung", "country": "KR", "language": "ko", "canon_tier": "letterboxd_top", "movement_tags": "Cannes Grand Prix, Corridor Single-Take, Greek Vengeance Tragedy", "rating_score": 8.9},
    {"title": "Memories of Murder", "year": 2003, "director": "Bong Joon-ho", "genre": "Crime, Drama, Mystery, Thriller", "cinematographer": "Kim Hyung-koo", "composer": "Taro Iwashiro", "screenwriter": "Bong Joon-ho, Shim Sung-bo", "country": "KR", "language": "ko", "canon_tier": "criterion_essential", "movement_tags": "Korean Rural Noir, Unresolved Cold Case, Tonal Mastery", "rating_score": 8.9},
    {"title": "Lost in Translation", "year": 2003, "director": "Sofia Coppola", "genre": "Comedy, Drama", "cinematographer": "Lance Acord", "composer": "Kevin Shields", "screenwriter": "Sofia Coppola", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Tokyo Hotel Melancholy, Shoegaze Atmosphere, Transient Connection", "rating_score": 8.7},
    {"title": "Elephant", "year": 2003, "director": "Gus Van Sant", "genre": "Crime, Drama", "cinematographer": "Harris Savides", "composer": "Ludwig van Beethoven", "screenwriter": "Gus Van Sant", "country": "US", "language": "en", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Steadicam High School Hallways, Tragic Stillness", "rating_score": 8.5},
    {"title": "City of God", "year": 2002, "director": "Fernando Meirelles, Kátia Lund", "genre": "Crime, Drama", "cinematographer": "César Charlone", "composer": "Antonio Pinto, Ed Côrtes", "screenwriter": "Bráulio Mantovani", "country": "BR", "language": "pt", "canon_tier": "letterboxd_top", "movement_tags": "Rio Favela Epic, Kinetic Editing, Sun-Drenched Brazilian Noir", "rating_score": 9.0},
    {"title": "Talk to Her", "year": 2002, "director": "Pedro Almodóvar", "genre": "Drama, Mystery, Romance", "cinematographer": "Javier Aguirresarobe", "composer": "Alberto Iglesias", "screenwriter": "Pedro Almodóvar", "country": "ES", "language": "es", "canon_tier": "sight_and_sound", "movement_tags": "Spanish Melodrama, Pina Bausch Dance, Alberto Iglesias Strings", "rating_score": 8.7},
    {"title": "Punch-Drunk Love", "year": 2002, "director": "Paul Thomas Anderson", "genre": "Comedy, Drama, Romance", "cinematographer": "Robert Elswit", "composer": "Jon Brion", "screenwriter": "Paul Thomas Anderson", "country": "US", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "Cannes Best Director, Anamorphic Blue Flares, Jon Brion Percussion", "rating_score": 8.6},
    {"title": "Mulholland Drive", "year": 2001, "director": "David Lynch", "genre": "Mystery, Drama, Thriller", "cinematographer": "Peter Deming", "composer": "Angelo Badalamenti", "screenwriter": "David Lynch", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound Top 10, Surrealism, Neo-Noir, Hollywood Nightmare", "rating_score": 9.1},
    {"title": "Spirited Away", "year": 2001, "director": "Hayao Miyazaki", "genre": "Animation, Adventure, Family, Fantasy", "cinematographer": "Atsushi Okui", "composer": "Joe Hisaishi", "screenwriter": "Hayao Miyazaki", "country": "JP", "language": "ja", "canon_tier": "letterboxd_top", "movement_tags": "Studio Ghibli, Hand-Drawn Animation, Shinto Folk Fantasy, Hisaishi Piano", "rating_score": 9.0},
    {"title": "The Piano Teacher", "year": 2001, "director": "Michael Haneke", "genre": "Drama, Music", "cinematographer": "Christian Berger", "composer": "Franz Schubert", "screenwriter": "Michael Haneke", "country": "FR", "language": "fr", "canon_tier": "palme_dor_festival", "movement_tags": "Cannes Grand Prix, Huppert Tour de Force, Schubert Subversion", "rating_score": 8.6},
    {"title": "In the Mood for Love", "year": 2000, "director": "Wong Kar-wai", "genre": "Drama, Romance", "cinematographer": "Christopher Doyle, Mark Lee Ping-bin", "composer": "Michael Galasso, Shigeru Umebayashi", "screenwriter": "Wong Kar-wai", "country": "HK", "language": "yue", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound #5, Poetic Romance, Step-Printing, Qipao Silhouettes", "rating_score": 9.2},
    {"title": "Yi Yi", "year": 2000, "director": "Edward Yang", "genre": "Drama, Romance", "cinematographer": "Yang Wei-han", "composer": "Peng Kaili", "screenwriter": "Edward Yang", "country": "TW", "language": "zh", "canon_tier": "sight_and_sound", "movement_tags": "Taiwanese New Cinema, Humanist Monolith, Urban Melancholy", "rating_score": 9.0},
    {"title": "Memento", "year": 2000, "director": "Christopher Nolan", "genre": "Mystery, Thriller", "cinematographer": "Wally Pfister", "composer": "David Julyan", "screenwriter": "Christopher Nolan", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Reverse Chronology, Amnesiac Neo-Noir, Pfister Monochrome", "rating_score": 8.7},
    {"title": "Beau Travail", "year": 1999, "director": "Claire Denis", "genre": "Drama", "cinematographer": "Agnès Godard", "composer": "Erki-Sven Tüür, Neil Tennant", "screenwriter": "Claire Denis, Jean-Pol Fargeau", "country": "FR", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound #7, Sensory Cinema, French Foreign Legion, Existential Drama", "rating_score": 8.9},
    {"title": "Magnolia", "year": 1999, "director": "Paul Thomas Anderson", "genre": "Drama", "cinematographer": "Robert Elswit", "composer": "Jon Brion, Aimee Mann", "screenwriter": "Paul Thomas Anderson", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Berlin Golden Bear, Interlocking Mosaic, Aimee Mann Score, Frogs", "rating_score": 8.8},
    {"title": "Eyes Wide Shut", "year": 1999, "director": "Stanley Kubrick", "genre": "Drama, Mystery, Thriller", "cinematographer": "Larry Smith", "composer": "Jocelyn Pook", "screenwriter": "Stanley Kubrick, Frederic Raphael", "country": "GB", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Kubrick Final Testament, Nocturnal Manhattan, Jocelyn Pook Masks", "rating_score": 8.8},
    {"title": "The Big Lebowski", "year": 1998, "director": "Joel Coen, Ethan Coen", "genre": "Comedy, Crime", "cinematographer": "Roger Deakins", "composer": "Carter Burwell", "screenwriter": "Joel Coen, Ethan Coen", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Zen Stoner Noir, Deakins Los Angeles, The Dude Abides", "rating_score": 8.8},
    {"title": "Princess Mononoke", "year": 1997, "director": "Hayao Miyazaki", "genre": "Animation, Action, Adventure, Fantasy", "cinematographer": "Atsushi Okui", "composer": "Joe Hisaishi", "screenwriter": "Hayao Miyazaki", "country": "JP", "language": "ja", "canon_tier": "letterboxd_top", "movement_tags": "Studio Ghibli, Ecological Mythology, Epic Fantasy", "rating_score": 8.9},
    {"title": "Taste of Cherry", "year": 1997, "director": "Abbas Kiarostami", "genre": "Drama", "cinematographer": "Homayoun Payvar", "composer": "None", "screenwriter": "Abbas Kiarostami", "country": "IR", "language": "fa", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Car Window Conversations, Iranian Humanism", "rating_score": 8.6},
    {"title": "Cure", "year": 1997, "director": "Kiyoshi Kurosawa", "genre": "Crime, Horror, Mystery, Thriller", "cinematographer": "Tokushô Kikumura", "composer": "Gary Ashiya", "screenwriter": "Kiyoshi Kurosawa", "country": "JP", "language": "ja", "canon_tier": "criterion_essential", "movement_tags": "J-Horror Psychological, Hypnotic Nihilism, Ambient Sound Masterpiece", "rating_score": 8.7},
    {"title": "Happy Together", "year": 1997, "director": "Wong Kar-wai", "genre": "Drama, Romance", "cinematographer": "Christopher Doyle", "composer": "Danny Chung", "screenwriter": "Wong Kar-wai", "country": "HK", "language": "yue", "canon_tier": "criterion_essential", "movement_tags": "Cannes Best Director, Buenos Aires Exile, Tango & Waterfall Melancholy", "rating_score": 8.6},
    {"title": "Fargo", "year": 1996, "director": "Joel Coen, Ethan Coen", "genre": "Crime, Drama, Thriller", "cinematographer": "Roger Deakins", "composer": "Carter Burwell", "screenwriter": "Joel Coen, Ethan Coen", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Minnesota Snow Noir, Coen Dark Irony, Scandinavian Strings", "rating_score": 8.9},
    {"title": "La Haine", "year": 1995, "director": "Mathieu Kassovitz", "genre": "Drama, Crime", "cinematographer": "Pierre Aïm", "composer": "Assassin", "screenwriter": "Mathieu Kassovitz", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "Banlieue Cinema, High-Contrast Monochrome, Urban Kineticism", "rating_score": 8.8},
    {"title": "Heat", "year": 1995, "director": "Michael Mann", "genre": "Action, Crime, Drama, Thriller", "cinematographer": "Dante Spinotti", "composer": "Elliot Goldenthal", "screenwriter": "Michael Mann", "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "LA Architectural Crime, High-Stakes Professionalism, Echoing Gunfire", "rating_score": 8.9},
    {"title": "Fallen Angels", "year": 1995, "director": "Wong Kar-wai", "genre": "Comedy, Crime, Drama, Romance", "cinematographer": "Christopher Doyle", "composer": "Frankie Chan, Roel A. García", "screenwriter": "Wong Kar-wai", "country": "HK", "language": "yue", "canon_tier": "criterion_essential", "movement_tags": "Ultra Wide Angle Neon, Hong Kong Nocturnal, Doyle Handheld", "rating_score": 8.7},
    {"title": "Ghost in the Shell", "year": 1995, "director": "Mamoru Oshii", "genre": "Animation, Action, Crime, Sci-Fi", "cinematographer": "Hisao Shirai", "composer": "Kenji Kawai", "screenwriter": "Kazunori Itō", "country": "JP", "language": "ja", "canon_tier": "cult_classic", "movement_tags": "Philosophical Cyberpunk, Transhumanism, Choral Chant", "rating_score": 8.8},
    {"title": "Chungking Express", "year": 1994, "director": "Wong Kar-wai", "genre": "Comedy, Drama, Romance", "cinematographer": "Christopher Doyle, Andrew Lau", "composer": "Frankie Chan, Roel A. García", "screenwriter": "Wong Kar-wai", "country": "HK", "language": "yue", "canon_tier": "sight_and_sound", "movement_tags": "California Dreamin', Step-Printing, Midnight Express Romance", "rating_score": 8.9},
    {"title": "Three Colors: Red", "year": 1994, "director": "Krzysztof Kieślowski", "genre": "Drama, Mystery, Romance", "cinematographer": "Piotr Sobociński", "composer": "Zbigniew Preisner", "screenwriter": "Krzysztof Kieślowski, Krzysztof Piesiewicz", "country": "FR", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "European Modernism, Fraternity & Fate, Masterpiece Finale", "rating_score": 8.9},
    {"title": "Three Colors: Blue", "year": 1993, "director": "Krzysztof Kieślowski", "genre": "Drama, Music", "cinematographer": "Sławomir Idziak", "composer": "Zbigniew Preisner", "screenwriter": "Krzysztof Kieślowski, Krzysztof Piesiewicz", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "Venice Golden Lion, Grief & Liberty, Color Symbolic", "rating_score": 8.8},
    {"title": "The Double Life of Véronique", "year": 1991, "director": "Krzysztof Kieślowski", "genre": "Drama, Fantasy, Music", "cinematographer": "Sławomir Idziak", "composer": "Zbigniew Preisner", "screenwriter": "Krzysztof Kieślowski, Krzysztof Piesiewicz", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "Poetic Realism, Golden Palette, Metaphysical Mystery", "rating_score": 8.7},
    {"title": "A Brighter Summer Day", "year": 1991, "director": "Edward Yang", "genre": "Crime, Drama, Romance", "cinematographer": "Zhang Hui-gong", "composer": "Zhan Hongda", "screenwriter": "Edward Yang, Hung Hung, Lai Mingtang, Alex Yang", "country": "TW", "language": "zh", "canon_tier": "sight_and_sound", "movement_tags": "Taiwanese New Cinema, Historical Epic, Coming of Age", "rating_score": 9.1},
    {"title": "Close-Up", "year": 1990, "director": "Abbas Kiarostami", "genre": "Drama, Documentary", "cinematographer": "Ali Reza Zarrindast", "composer": "Kambiz Roshanravan", "screenwriter": "Abbas Kiarostami", "country": "IR", "language": "fa", "canon_tier": "sight_and_sound", "movement_tags": "Iranian New Wave, Docufiction, Meta-Cinema", "rating_score": 8.9},
    {"title": "Do the Right Thing", "year": 1989, "director": "Spike Lee", "genre": "Comedy, Drama", "cinematographer": "Ernest Dickerson", "composer": "Bill Lee, Public Enemy", "screenwriter": "Spike Lee", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Bed-Stuy Heatwave, Dutch Angles, Fight the Power", "rating_score": 8.9},
    {"title": "Cinema Paradiso", "year": 1988, "director": "Giuseppe Tornatore", "genre": "Drama, Romance", "cinematographer": "Blasco Giurato", "composer": "Ennio Morricone, Andrea Morricone", "screenwriter": "Giuseppe Tornatore", "country": "IT", "language": "it", "canon_tier": "letterboxd_top", "movement_tags": "Love Letter to Cinema, Nostalgic Masterpiece, Morricone Score", "rating_score": 8.9},
    {"title": "Akira", "year": 1988, "director": "Katsuhiro Otomo", "genre": "Animation, Action, Sci-Fi", "cinematographer": "Katsuji Misawa", "composer": "Shoji Yamashiro", "screenwriter": "Katsuhiro Otomo, Izo Hashimoto", "country": "JP", "language": "ja", "canon_tier": "cult_classic", "movement_tags": "Cyberpunk Landmark, Neo-Tokyo Destruction, Hand-Drawn 24fps", "rating_score": 8.8},
    {"title": "Wings of Desire", "year": 1987, "director": "Wim Wenders", "genre": "Drama, Fantasy, Romance", "cinematographer": "Henri Alekan", "composer": "Jürgen Knieper", "screenwriter": "Wim Wenders, Peter Handke", "country": "DE", "language": "de", "canon_tier": "sight_and_sound", "movement_tags": "Cannes Best Director, Divided Berlin, Guardian Angels, B&W to Color", "rating_score": 8.8},
    {"title": "Blue Velvet", "year": 1986, "director": "David Lynch", "genre": "Drama, Mystery, Thriller", "cinematographer": "Frederick Elmes", "composer": "Angelo Badalamenti", "screenwriter": "David Lynch", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Suburban Night Terror, Ear in the Grass, Roy Orbison", "rating_score": 8.8},
    {"title": "Ran", "year": 1985, "director": "Akira Kurosawa", "genre": "Action, Drama, War", "cinematographer": "Takao Saito, Masaharu Ueda, Asakazu Nakai", "composer": "Toru Takemitsu", "screenwriter": "Akira Kurosawa, Hideo Oguni, Masato Ide", "country": "JP", "language": "ja", "canon_tier": "sight_and_sound", "movement_tags": "Late Kurosawa Color Epic, King Lear, Blood on Silk", "rating_score": 9.1},
    {"title": "Come and See", "year": 1985, "director": "Elem Klimov", "genre": "Drama, War", "cinematographer": "Aleksei Rodionov", "composer": "Oleg Yanchenko", "screenwriter": "Ales Adamovich, Elem Klimov", "country": "SU", "language": "ru", "canon_tier": "sight_and_sound", "movement_tags": "Belarusian Nightmare, Steadicam Horror, War Tragedy", "rating_score": 9.0},
    {"title": "Paris, Texas", "year": 1984, "director": "Wim Wenders", "genre": "Drama", "cinematographer": "Robby Müller", "composer": "Ry Cooder", "screenwriter": "L.M. Kit Carson, Sam Shepard", "country": "DE", "language": "en", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Ry Cooder Slide Guitar, Peep Show Monologue", "rating_score": 8.9},
    {"title": "Blade Runner", "year": 1982, "director": "Ridley Scott", "genre": "Sci-Fi, Thriller", "cinematographer": "Jordan Cronenweth", "composer": "Vangelis", "screenwriter": "Hampton Fancher, David Peoples", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Cyberpunk Foundation, Synth Atmosphere, Neon Rain", "rating_score": 8.9},
    {"title": "Thief", "year": 1981, "director": "Michael Mann", "genre": "Action, Crime, Drama, Thriller", "cinematographer": "Donald E. Thorin", "composer": "Tangerine Dream", "screenwriter": "Michael Mann", "country": "US", "language": "en", "canon_tier": "criterion_essential", "movement_tags": "Tangerine Dream Synth, Wet Chicago Asphalt, Pure Code of Ethics", "rating_score": 8.6},
    {"title": "Raging Bull", "year": 1980, "director": "Martin Scorsese", "genre": "Biography, Drama, Sport", "cinematographer": "Michael Chapman", "composer": "Pietro Mascagni", "screenwriter": "Paul Schrader, Mardik Martin", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Black & White Kinetic, Violent Grace, Schoonmaker Editing", "rating_score": 8.9},

    # =========================================================================
    # 3. GOLDEN AGE MONOLITHS (< 1980)
    # =========================================================================
    {"title": "Apocalypse Now", "year": 1979, "director": "Francis Ford Coppola", "genre": "Drama, Mystery, War", "cinematographer": "Vittorio Storaro", "composer": "Carmine Coppola, Francis Ford Coppola", "screenwriter": "John Milius, Francis Ford Coppola", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Palme d'Or Winner, Storaro Light & Shadow, Hallucinatory Vietnam", "rating_score": 9.2},
    {"title": "Stalker", "year": 1979, "director": "Andrei Tarkovsky", "genre": "Sci-Fi, Drama", "cinematographer": "Aleksandr Knyazhinsky", "composer": "Eduard Artemyev", "screenwriter": "Arkady Strugatsky, Boris Strugatsky, Andrei Tarkovsky", "country": "SU", "language": "ru", "canon_tier": "sight_and_sound", "movement_tags": "Poetic Sci-Fi, Sculpting in Time, Philosophical Room", "rating_score": 9.0},
    {"title": "Suspiria", "year": 1977, "director": "Dario Argento", "genre": "Horror, Mystery", "cinematographer": "Luciano Tovoli", "composer": "Goblin, Dario Argento", "screenwriter": "Dario Argento, Daria Nicolodi", "country": "IT", "language": "it", "canon_tier": "cult_classic", "movement_tags": "Italian Giallo, Technicolor Nightmare, Progressive Rock Score", "rating_score": 8.5},
    {"title": "Taxi Driver", "year": 1976, "director": "Martin Scorsese", "genre": "Crime, Drama", "cinematographer": "Michael Chapman", "composer": "Bernard Herrmann", "screenwriter": "Paul Schrader", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Palme d'Or Winner, Urban Hell, Schrader Solitary Man", "rating_score": 9.1},
    {"title": "Barry Lyndon", "year": 1975, "director": "Stanley Kubrick", "genre": "Adventure, Drama, History, War", "cinematographer": "John Alcott", "composer": "George Frideric Handel, Franz Schubert", "screenwriter": "Stanley Kubrick", "country": "GB", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Candlelight Lenses, Painterly Stillness, 18th Century Irony", "rating_score": 9.0},
    {"title": "Mirror", "year": 1975, "director": "Andrei Tarkovsky", "genre": "Drama, History", "cinematographer": "Georgy Rerberg", "composer": "Eduard Artemyev", "screenwriter": "Andrei Tarkovsky, Aleksandr Misharin", "country": "SU", "language": "ru", "canon_tier": "sight_and_sound", "movement_tags": "Poetic Auto-Fiction, Russian Masterpiece, Memory Matrix", "rating_score": 9.0},
    {"title": "Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles", "year": 1975, "director": "Chantal Akerman", "genre": "Drama", "cinematographer": "Babette Mangolte", "composer": "None", "screenwriter": "Chantal Akerman", "country": "BE", "language": "fr", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound #1, Feminist Avant-Garde, Structuralist, Slow Cinema", "rating_score": 8.9},
    {"title": "The Godfather Part II", "year": 1974, "director": "Francis Ford Coppola", "genre": "Crime, Drama", "cinematographer": "Gordon Willis", "composer": "Nino Rota, Carmine Coppola", "screenwriter": "Francis Ford Coppola, Mario Puzo", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "New Hollywood, Dual Timelines, Corruption of Power", "rating_score": 9.2},
    {"title": "Chinatown", "year": 1974, "director": "Roman Polanski", "genre": "Drama, Mystery, Thriller", "cinematographer": "John A. Alonzo", "composer": "Jerry Goldsmith", "screenwriter": "Robert Towne", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Neo-Noir Definite, Drought & Greed, Tragedy Screenplay", "rating_score": 9.0},
    {"title": "The Conversation", "year": 1974, "director": "Francis Ford Coppola", "genre": "Drama, Mystery, Thriller", "cinematographer": "Bill Butler, Haskell Wexler", "composer": "David Shire", "screenwriter": "Francis Ford Coppola", "country": "US", "language": "en", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Paranoia Thriller, Sound Design Masterclass", "rating_score": 8.8},
    {"title": "The Godfather", "year": 1972, "director": "Francis Ford Coppola", "genre": "Crime, Drama", "cinematographer": "Gordon Willis", "composer": "Nino Rota", "screenwriter": "Mario Puzo, Francis Ford Coppola", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "New Hollywood, American Epic, Shadow Photography", "rating_score": 9.3},
    {"title": "Army of Shadows", "year": 1969, "director": "Jean-Pierre Melville", "genre": "Drama, War, Thriller", "cinematographer": "Pierre Lhomme, Walter Wottitz", "composer": "Eric Demarsan", "screenwriter": "Jean-Pierre Melville", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "French Resistance, Cold Realism, Espionage Masterwork", "rating_score": 8.9},
    {"title": "2001: A Space Odyssey", "year": 1968, "director": "Stanley Kubrick", "genre": "Sci-Fi, Mystery", "cinematographer": "Geoffrey Unsworth, John Alcott", "composer": "György Ligeti, Richard Strauss", "screenwriter": "Stanley Kubrick, Arthur C. Clarke", "country": "GB", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Philosophical Sci-Fi, Monumental Cinema, Starchild", "rating_score": 9.2},
    {"title": "Once Upon a Time in the West", "year": 1968, "director": "Sergio Leone", "genre": "Western", "cinematographer": "Tonino Delli Colli", "composer": "Ennio Morricone", "screenwriter": "Sergio Donati, Sergio Leone, Dario Argento, Bernardo Bertolucci", "country": "IT", "language": "it", "canon_tier": "sight_and_sound", "movement_tags": "Spaghetti Western, Monumental Operatic, Harmonica Theme", "rating_score": 9.0},
    {"title": "Le Samouraï", "year": 1967, "director": "Jean-Pierre Melville", "genre": "Crime, Drama, Thriller", "cinematographer": "Henri Decaë", "composer": "François de Roubaix", "screenwriter": "Jean-Pierre Melville", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "French Polar, Cool Existentialism, Neo-Noir Blueprint", "rating_score": 8.8},
    {"title": "Blow-Up", "year": 1966, "director": "Michelangelo Antonioni", "genre": "Drama, Mystery, Thriller", "cinematographer": "Carlo Di Palma", "composer": "Herbie Hancock", "screenwriter": "Michelangelo Antonioni, Tonino Guerra", "country": "GB", "language": "en", "canon_tier": "palme_dor_festival", "movement_tags": "Palme d'Or Winner, Swinging London, Epistemological Mystery", "rating_score": 8.7},
    {"title": "Persona", "year": 1966, "director": "Ingmar Bergman", "genre": "Drama, Mystery", "cinematographer": "Sven Nykvist", "composer": "Lars Johan Werle", "screenwriter": "Ingmar Bergman", "country": "SE", "language": "sv", "canon_tier": "sight_and_sound", "movement_tags": "Modernist Masterpiece, Psychological Identity, Sven Nykvist", "rating_score": 8.9},
    {"title": "High and Low", "year": 1963, "director": "Akira Kurosawa", "genre": "Crime, Drama, Mystery, Thriller", "cinematographer": "Asakazu Nakai, Takao Saito", "composer": "Masaru Sato", "screenwriter": "Akira Kurosawa, Hideo Oguni, Ryūzō Kikushima, Eijirō Hisaita", "country": "JP", "language": "ja", "canon_tier": "criterion_essential", "movement_tags": "Japanese Noir, Social Class Division, Procedural Tension", "rating_score": 8.9},
    {"title": "8½", "year": 1963, "director": "Federico Fellini", "genre": "Drama, Fantasy", "cinematographer": "Gianni Di Venanzo", "composer": "Nino Rota", "screenwriter": "Federico Fellini, Ennio Flaiano, Tullio Pinelli, Brunello Rondi", "country": "IT", "language": "it", "canon_tier": "sight_and_sound", "movement_tags": "Italian Golden Age, Meta-Cinema, Dream Realism", "rating_score": 9.0},
    {"title": "Harakiri", "year": 1962, "director": "Masaki Kobayashi", "genre": "Action, Drama, Mystery", "cinematographer": "Yoshio Miyajima", "composer": "Toru Takemitsu", "screenwriter": "Shinobu Hashimoto", "country": "JP", "language": "ja", "canon_tier": "criterion_essential", "movement_tags": "Cannes Special Jury Prize, Anti-Samurai, Moral Intensity", "rating_score": 9.0},
    {"title": "Cleo from 5 to 7", "year": 1962, "director": "Agnès Varda", "genre": "Drama, Music", "cinematographer": "Jean Rabier", "composer": "Michel Legrand", "screenwriter": "Agnès Varda", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "Left Bank, Real-Time Cinema, Flâneuse Paris", "rating_score": 8.7},
    {"title": "L'Avventura", "year": 1960, "director": "Michelangelo Antonioni", "genre": "Drama, Mystery, Romance", "cinematographer": "Aldo Scavarda", "composer": "Giovanni Fusco", "screenwriter": "Michelangelo Antonioni, Elio Bartolini, Tonino Guerra", "country": "IT", "language": "it", "canon_tier": "sight_and_sound", "movement_tags": "Italian Modernism, Incommunicability, Architecture of Alienation", "rating_score": 8.7},
    {"title": "La Dolce Vita", "year": 1960, "director": "Federico Fellini", "genre": "Comedy, Drama", "cinematographer": "Otello Martelli", "composer": "Nino Rota", "screenwriter": "Federico Fellini, Ennio Flaiano, Tullio Pinelli", "country": "IT", "language": "it", "canon_tier": "sight_and_sound", "movement_tags": "Palme d'Or Winner, Roman Decadence, Existential Celebrity", "rating_score": 8.9},
    {"title": "Breathless", "year": 1960, "director": "Jean-Luc Godard", "genre": "Crime, Drama", "cinematographer": "Raoul Coutard", "composer": "Martial Solal", "screenwriter": "Jean-Luc Godard", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "French New Wave, Jump Cuts, Revolutionary Form", "rating_score": 8.8},
    {"title": "The 400 Blows", "year": 1959, "director": "François Truffaut", "genre": "Drama", "cinematographer": "Henri Decaë", "composer": "Jean Constantin", "screenwriter": "François Truffaut, Marcel Moussy", "country": "FR", "language": "fr", "canon_tier": "criterion_essential", "movement_tags": "Cannes Best Director, French New Wave, Freeze Frame Finale", "rating_score": 9.0},
    {"title": "Vertigo", "year": 1958, "director": "Alfred Hitchcock", "genre": "Mystery, Romance, Thriller", "cinematographer": "Robert Burks", "composer": "Bernard Herrmann", "screenwriter": "Alec Coppel, Samuel A. Taylor", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound #2, Psychological Thriller, Color Masterwork", "rating_score": 9.1},
    {"title": "Seven Samurai", "year": 1954, "director": "Akira Kurosawa", "genre": "Action, Drama", "cinematographer": "Asakazu Nakai", "composer": "Fumio Hayasaka", "screenwriter": "Akira Kurosawa, Shinobu Hashimoto, Hideo Oguni", "country": "JP", "language": "ja", "canon_tier": "sight_and_sound", "movement_tags": "Japanese Golden Age, Jidaigeki, Dynamic Montage", "rating_score": 9.2},
    {"title": "Tokyo Story", "year": 1953, "director": "Yasujirō Ozu", "genre": "Drama", "cinematographer": "Yūharu Atsuta", "composer": "Kojun Saitō", "screenwriter": "Kōgo Noda, Yasujirō Ozu", "country": "JP", "language": "ja", "canon_tier": "sight_and_sound", "movement_tags": "Sight & Sound #4, Tatami Shot, Family Melodrama", "rating_score": 9.2},
    {"title": "Rashomon", "year": 1950, "director": "Akira Kurosawa", "genre": "Crime, Drama, Mystery", "cinematographer": "Kazuo Miyagawa", "composer": "Fumio Hayasaka", "screenwriter": "Akira Kurosawa, Shinobu Hashimoto", "country": "JP", "language": "ja", "canon_tier": "sight_and_sound", "movement_tags": "Venice Golden Lion, Subjective Truth, Forest Lighting", "rating_score": 8.9},
    {"title": "Bicycle Thieves", "year": 1948, "director": "Vittorio De Sica", "genre": "Drama", "cinematographer": "Carlo Montuori", "composer": "Alessandro Cicognini", "screenwriter": "Cesare Zavattini", "country": "IT", "language": "it", "canon_tier": "sight_and_sound", "movement_tags": "Italian Neorealism, Post-War Rome, Humanist Tragedy", "rating_score": 8.9},
    {"title": "Citizen Kane", "year": 1941, "director": "Orson Welles", "genre": "Drama, Mystery", "cinematographer": "Gregg Toland", "composer": "Bernard Herrmann", "screenwriter": "Herman J. Mankiewicz, Orson Welles", "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Deep Focus, Flashback Structure, Rosebud Monolith", "rating_score": 9.1},
    # =========================================================================
    # 4. PRESTIGE TELEVISION MASTERWORKS (Golden Age, Modern Cult & Contemporary)
    # =========================================================================
    {"title": "Severance", "year": 2022, "director": "Dan Erickson, Ben Stiller", "genre": "Drama, Mystery, Sci-Fi", "poster": "https://image.tmdb.org/t/p/w500/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Apple TV+, Dystopian Workplace, Psychological Thriller, Lumon Mystery", "rating_score": 8.9},
    {"title": "Succession", "year": 2018, "director": "Jesse Armstrong, Mark Mylod", "genre": "Drama, Comedy", "poster": "https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "HBO, Corporate Shakespeare, Brit-Satire Dialogue, Nicholas Britell Score", "rating_score": 9.0},
    {"title": "Chernobyl", "year": 2019, "director": "Craig Mazin, Johan Renck", "genre": "Drama, History, Thriller", "poster": "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "HBO Miniseries, Nuclear Catastrophe, Hildur Guðnadóttir Soundscape", "rating_score": 9.2},
    {"title": "Mindhunter", "year": 2017, "director": "David Fincher, Joe Penhall", "genre": "Crime, Drama, Thriller", "poster": "https://image.tmdb.org/t/p/w500/fbKE87mojpIETWepSbD5Qt741fp.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Fincher Precision, FBI Behavioral Science, Serial Killer Profiling", "rating_score": 8.8},
    {"title": "The Bear", "year": 2022, "director": "Christopher Storer", "genre": "Comedy, Drama", "poster": "https://image.tmdb.org/t/p/w500/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "FX, Culinary Chaos, Chicago Kitchen, High-Anxiety One-Take", "rating_score": 8.8},
    {"title": "Dark", "year": 2017, "director": "Baran bo Odar, Jantje Friese", "genre": "Crime, Drama, Mystery, Sci-Fi", "poster": "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg", "tv_show": 1, "country": "DE", "language": "de", "canon_tier": "letterboxd_top", "movement_tags": "German Masterwork, Time Travel Paradox, Winden Labyrinth, Determinism", "rating_score": 8.9},
    {"title": "True Detective", "year": 2014, "director": "Nic Pizzolatto, Cary Joji Fukunaga", "genre": "Crime, Drama, Mystery, Thriller", "poster": "https://image.tmdb.org/t/p/w500/dC7jkj2g1aU8sxKqM6D4g44xA6w.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "HBO Season 1, Southern Gothic Noir, Cosmic Nihilism, Rust Cohle", "rating_score": 9.1},
    {"title": "Shōgun", "year": 2024, "director": "Justin Marks, Rachel Kondo", "genre": "Drama, History, War", "poster": "https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg", "tv_show": 1, "country": "US", "language": "ja", "canon_tier": "letterboxd_top", "movement_tags": "FX Masterpiece, Feudal Japan Political Intrigue, Toranaga Grand Strategy", "rating_score": 8.9},
    {"title": "Arcane", "year": 2021, "director": "Christian Linke, Alex Yee", "genre": "Animation, Action, Sci-Fi, Drama", "poster": "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn397F62G96HN.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Fortiche 2.5D Animation, Piltover Steampunk, Tragic Sisterhood", "rating_score": 9.1},
    {"title": "Scavengers Reign", "year": 2023, "director": "Joseph Bennett, Charles Huettner", "genre": "Animation, Sci-Fi, Adventure, Drama", "poster": "https://image.tmdb.org/t/p/w500/bFlVZV8TQbs8hcIY7PVYonYFMgK.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Moebius Biopunk, Alien Ecosystem, Visual Poetry, Max Masterpiece", "rating_score": 8.9},
    {"title": "Better Call Saul", "year": 2015, "director": "Vince Gilligan, Peter Gould", "genre": "Crime, Drama", "poster": "https://image.tmdb.org/t/p/w500/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Breaking Bad Universe, Jimmy McGill Moral Tragedy, Legal Noir", "rating_score": 9.0},
    {"title": "Fleabag", "year": 2016, "director": "Phoebe Waller-Bridge", "genre": "Comedy, Drama", "poster": "https://image.tmdb.org/t/p/w500/27vEYsRKa3eAniwmoccOoluEXQ1.jpg", "tv_show": 1, "country": "GB", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "BBC Masterwork, Fourth Wall Breaking, Modern Female Confession", "rating_score": 8.9},
    {"title": "Twin Peaks", "year": 1990, "director": "David Lynch, Mark Frost", "genre": "Drama, Mystery, Sci-Fi, Horror", "poster": "https://image.tmdb.org/t/p/w500/lA9CNSdo50iQPZ8A2fyVpMvJZAf.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Lynchian Surrealism, Laura Palmer Mystery, Angelo Badalamenti Score", "rating_score": 9.2},
    {"title": "The Wire", "year": 2002, "director": "David Simon", "genre": "Crime, Drama, Thriller", "poster": "https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "HBO Sociological Great, Baltimore Institutions, Urban Realism", "rating_score": 9.3},
    {"title": "The Sopranos", "year": 1999, "director": "David Chase", "genre": "Crime, Drama", "poster": "https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "HBO Prestige Revolution, Tony Soprano Psychoanalysis, Mafia Deconstruction", "rating_score": 9.2},
    {"title": "Cowboy Bebop", "year": 1998, "director": "Shinichirō Watanabe", "genre": "Animation, Action, Sci-Fi, Adventure", "poster": "https://image.tmdb.org/t/p/w500/xDiXDfZwC6XYC6fxHI1jl3A3Ill.jpg", "tv_show": 1, "country": "JP", "language": "ja", "canon_tier": "sight_and_sound", "movement_tags": "Yoko Kanno Jazz, Space Western, Existential Noir Anime", "rating_score": 9.0},
    {"title": "Dekalog", "year": 1989, "director": "Krzysztof Kieślowski", "genre": "Drama", "poster": "https://image.tmdb.org/t/p/w500/16BknQDA9XzguaFr5nO1JyHaVBb.jpg", "tv_show": 1, "country": "PL", "language": "pl", "canon_tier": "sight_and_sound", "movement_tags": "Criterion Masterpiece, Ten Commandments, Warsaw Housing Moral Dilemmas", "rating_score": 9.2},
    {"title": "The Twilight Zone", "year": 1959, "director": "Rod Serling", "genre": "Drama, Fantasy, Horror, Mystery, Sci-Fi", "poster": "https://image.tmdb.org/t/p/w500/7uY4pCOxbEdv4M8jTE4uMPVoSIW.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "sight_and_sound", "movement_tags": "Serling Anthology, Golden Age TV, Sci-Fi Morality Parables", "rating_score": 9.0},
    {"title": "Fargo", "year": 2014, "director": "Noah Hawley", "genre": "Crime, Drama, Thriller", "poster": "https://image.tmdb.org/t/p/w500/a3VW6khsyUVKrG0GBCWFG3NzWPX.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "FX Coen Anthology, Midwestern Neo-Noir, Absurdist Crime", "rating_score": 8.8},
    {"title": "The Leftovers", "year": 2014, "director": "Damon Lindelof, Tom Perrotta", "genre": "Drama, Fantasy, Mystery", "poster": "https://image.tmdb.org/t/p/w500/NKJdryIFHr245Umq6gXsf7oULW.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "HBO Grief Meditation, Max Richter Score, Existential Departure", "rating_score": 8.9},
    {"title": "Mr. Robot", "year": 2015, "director": "Sam Esmail", "genre": "Crime, Drama, Thriller, Sci-Fi", "poster": "https://image.tmdb.org/t/p/w500/kv1nRqgebSsREnd7vdC2pSGjpLo.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "Cyberpunk Thriller, Dissociative Identity, Mac Quayle Synth", "rating_score": 8.8},
    {"title": "Band of Brothers", "year": 2001, "director": "Steven Spielberg, Tom Hanks", "genre": "Drama, History, War", "poster": "https://image.tmdb.org/t/p/w500/pGzV187ogXzgJrvPRy2YPi29ofH.jpg", "tv_show": 1, "country": "US", "language": "en", "canon_tier": "letterboxd_top", "movement_tags": "HBO WWII Masterpiece, Easy Company Brotherhood, Michael Kamen Score", "rating_score": 9.2}
]


def seed_corpus_database(force_reseed: bool = False):
    """Seeds the SQLite database with the curated cinephile masterworks."""
    _init_corpus_db()
    with sqlite3.connect(CORPUS_DB_PATH) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM curated_films")
        count = cursor.fetchone()[0]
        if count >= len(CORE_CINEPHILE_MASTERWORKS) and not force_reseed:
            return

        logger.info(f"[CORPUS SERVICE] Seeding {len(CORE_CINEPHILE_MASTERWORKS)} curated films into SQLite...")
        for film in CORE_CINEPHILE_MASTERWORKS:
            key = _normalize_key(film["title"], film["year"])
            cursor.execute("SELECT poster FROM curated_films WHERE movie_key = ?", (key,))
            existing_row = cursor.fetchone()
            existing_poster = existing_row[0] if existing_row else ""
            poster_to_use = film.get("poster") or existing_poster or ""

            cursor.execute("""
                INSERT OR REPLACE INTO curated_films 
                (movie_key, title, year, director, genre, cinematographer, composer, screenwriter, studios, lead_actors, country, language, overview, poster, tv_show, canon_tier, movement_tags, rating_score)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                key,
                film["title"],
                int(film["year"]),
                film["director"],
                film["genre"],
                film.get("cinematographer", ""),
                film.get("composer", ""),
                film.get("screenwriter", ""),
                film.get("studios", ""),
                film.get("lead_actors", ""),
                film.get("country", "US"),
                film.get("language", "en"),
                film.get("overview", ""),
                poster_to_use,
                film.get("tv_show", 0),
                film.get("canon_tier", "landmark"),
                film.get("movement_tags", ""),
                film.get("rating_score", 8.5)
            ))
        conn.commit()
        logger.info("[CORPUS SERVICE] Seeding complete!")


def get_all_curated_films() -> List[Dict[str, Any]]:
    """
    Retrieves all curated masterworks with high-speed in-memory caching (< 2ms).
    """
    global _IN_MEMORY_CORPUS_CACHE
    if _IN_MEMORY_CORPUS_CACHE is not None:
        return _IN_MEMORY_CORPUS_CACHE

    _init_corpus_db()
    seed_corpus_database(force_reseed=False)

    with sqlite3.connect(CORPUS_DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM curated_films ORDER BY rating_score DESC, year DESC")
        rows = cursor.fetchall()
        films = [dict(r) for r in rows]

    _IN_MEMORY_CORPUS_CACHE = films
    return _IN_MEMORY_CORPUS_CACHE
